from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime, timezone

import pandas as pd

from martwin.workflows.digital_twin import TwinModel
from martwin.calibration.gap_analysis import GapReport


def matrix_to_markdown(matrix) -> str:
    rows = []
    for row in matrix:
        rows.append("| " + " | ".join(f"{float(x): .6f}" for x in row) + " |")
    header = "| r0 | r1 | r2 |\n|---:|---:|---:|"
    return header + "\n" + "\n".join(rows)


def build_markdown_report(
    model: TwinModel,
    assignment_summary: pd.DataFrame | None = None,
    metrics: dict | None = None,
    gap_report: GapReport | None = None,
    notes: str = "",
) -> str:
    metrics = metrics or {}
    orx = model.orientation_relationship
    lines = [
        "# OpenMartensiteTwin Analysis Report",
        "",
        f"Generated: {datetime.now(timezone.utc).isoformat()}",
        "",
        "## Configuration",
        "",
        f"- Material system: **{model.config.material_system}**",
        f"- Orientation relationship: **{orx.name}**",
        f"- Parent phase: `{orx.parent_phase}`",
        f"- Child phase: `{orx.child_phase}`",
        f"- Number of generated variants: **{len(model.variants)}**",
        f"- Angular tolerance: **{model.config.angular_tolerance_deg:.2f}°**",
        "",
        "## How to interpret this report",
        "",
        "This report separates model assumptions, measured/synthetic data, analysis outputs, and reliability warnings. A low data-confidence score means the model is running in theoretical or preliminary-analysis mode, not as a calibrated engineering twin.",
        "",
        "## Orientation relationship matrix",
        "",
        matrix_to_markdown(orx.matrix_child_to_parent),
        "",
        "## Source / interpretation note",
        "",
        orx.source_note,
        "",
        "## Key metrics",
        "",
    ]
    if metrics:
        for k, v in metrics.items():
            lines.append(f"- `{k}`: {v}")
    else:
        lines.append("No analysis metrics yet.")
    if assignment_summary is not None and not assignment_summary.empty:
        try:
            table_text = assignment_summary.to_markdown(index=False)
        except Exception:
            table_text = assignment_summary.to_string(index=False)
        lines += ["", "## Variant population summary", "", "This table reports how many analyzed map points were assigned to each theoretical variant. `count` is the number of points; `fraction` is the share of all analyzed points; `mean_error_deg` is the average angular mismatch for that variant.", "", table_text]
    if gap_report is not None:
        lines += [
            "",
            "## Data-gap assessment",
            "",
            f"- Confidence score: **{gap_report.confidence_score:.2f}**",
            f"- Missing data: {', '.join(gap_report.missing) if gap_report.missing else 'None'}",
            "",
            "Recommended next experiments:",
        ]
        for rec in gap_report.recommended_next_experiments:
            lines.append(f"- {rec}")
    if notes:
        lines += ["", "## Analyst notes", "", notes]
    lines += [
        "",
        "## Reliability warning",
        "",
        "This report is generated by a research software prototype. EBSD vendor conventions, lattice parameters, symmetry settings, parent/child orientation definitions, kinetic parameters, and measured sample-specific data must be validated before publication or industrial decision-making.",
    ]
    return "\n".join(lines)


def _json_safe(value):
    """Convert common scientific/Pandas objects into JSON-safe Python types."""
    try:
        import numpy as np
        if isinstance(value, np.generic):
            return value.item()
        if isinstance(value, np.ndarray):
            return value.tolist()
    except Exception:
        pass
    try:
        import pandas as pd
        if isinstance(value, pd.DataFrame):
            return value.to_dict(orient="records")
        if isinstance(value, pd.Series):
            return value.to_dict()
    except Exception:
        pass
    if isinstance(value, dict):
        return {str(k): _json_safe(v) for k, v in value.items()}
    if isinstance(value, (list, tuple, set)):
        return [_json_safe(v) for v in value]
    return value


def build_json_report(
    model: TwinModel,
    assignment_summary: pd.DataFrame | dict | None = None,
    metrics: dict | None = None,
    gap_report: GapReport | None = None,
    notes: str = "",
) -> dict:
    """Build a JSON-safe report payload.

    v0.5.4 had an interface mismatch: the Streamlit app called this function as
    build_json_report(model, assignment_summary, metrics, gap_report, notes=...),
    while the function was still defined as build_json_report(model, metrics, gap_report).
    This version accepts both call styles and returns a dict that the app can extend
    before calling json.dumps().
    """
    # Backward compatibility: build_json_report(model, metrics, gap_report)
    if isinstance(assignment_summary, dict) and (metrics is None or isinstance(metrics, GapReport)):
        if isinstance(metrics, GapReport) and gap_report is None:
            gap_report = metrics
        metrics = assignment_summary
        assignment_summary = None

    metrics = metrics or {}
    assignment_records = None
    if assignment_summary is not None:
        try:
            if hasattr(assignment_summary, "empty") and not assignment_summary.empty:
                assignment_records = assignment_summary.to_dict(orient="records")
        except Exception:
            assignment_records = str(assignment_summary)

    payload = {
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "configuration": asdict(model.config),
        "orientation_relationship": {
            "name": model.orientation_relationship.name,
            "parent_phase": model.orientation_relationship.parent_phase,
            "child_phase": model.orientation_relationship.child_phase,
            "matrix_child_to_parent": model.orientation_relationship.matrix_child_to_parent.tolist(),
            "source_note": getattr(model.orientation_relationship, "source_note", ""),
            "description": getattr(model.orientation_relationship, "description", getattr(model.orientation_relationship, "source_note", model.orientation_relationship.name)),
        },
        "n_variants": len(model.variants),
        "variant_population_summary": assignment_records,
        "metrics": metrics,
        "gap_report": asdict(gap_report) if gap_report else None,
        "notes": notes,
    }
    return _json_safe(payload)
