from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime, timezone

import pandas as pd

from martwin.workflows.digital_twin import TwinModel
from martwin.calibration.gap_analysis import GapReport


def matrix_to_markdown(matrix) -> str:
    rows = []
    for row in matrix:
        rows.append("| " + " | ".join(f"{float(x): .6f}" for x in row) + " |")
    header = "| r0 | r1 | r2 |\n|---:|---:|---:|"
    return header + "\n" + "\n".join(rows)


def build_markdown_report(
    model: TwinModel,
    assignment_summary: pd.DataFrame | None = None,
    metrics: dict | None = None,
    gap_report: GapReport | None = None,
    notes: str = "",
) -> str:
    metrics = metrics or {}
    orx = model.orientation_relationship
    lines = [
        "# OpenMartensiteTwin Analysis Report",
        "",
        f"Generated: {datetime.now(timezone.utc).isoformat()}",
        "",
        "## Configuration",
        "",
        f"- Material system: **{model.config.material_system}**",
        f"- Orientation relationship: **{orx.name}**",
        f"- Parent phase: `{orx.parent_phase}`",
        f"- Child phase: `{orx.child_phase}`",
        f"- Number of generated variants: **{len(model.variants)}**",
        f"- Angular tolerance: **{model.config.angular_tolerance_deg:.2f}°**",
        "",
        "## How to interpret this report",
        "",
        "This report separates model assumptions, measured/synthetic data, analysis outputs, and reliability warnings. A low data-confidence score means the model is running in theoretical or preliminary-analysis mode, not as a calibrated engineering twin.",
        "",
        "## Orientation relationship matrix",
        "",
        matrix_to_markdown(orx.matrix_child_to_parent),
        "",
        "## Source / interpretation note",
        "",
        orx.source_note,
        "",
        "## Key metrics",
        "",
    ]
    if metrics:
        for k, v in metrics.items():
            lines.append(f"- `{k}`: {v}")
    else:
        lines.append("No analysis metrics yet.")
    if assignment_summary is not None and not assignment_summary.empty:
        try:
            table_text = assignment_summary.to_markdown(index=False)
        except Exception:
            table_text = assignment_summary.to_string(index=False)
        lines += ["", "## Variant population summary", "", "This table reports how many analyzed map points were assigned to each theoretical variant. `count` is the number of points; `fraction` is the share of all analyzed points; `mean_error_deg` is the average angular mismatch for that variant.", "", table_text]
    if gap_report is not None:
        lines += [
            "",
            "## Data-gap assessment",
            "",
            f"- Confidence score: **{gap_report.confidence_score:.2f}**",
            f"- Missing data: {', '.join(gap_report.missing) if gap_report.missing else 'None'}",
            "",
            "Recommended next experiments:",
        ]
        for rec in gap_report.recommended_next_experiments:
            lines.append(f"- {rec}")
    if notes:
        lines += ["", "## Analyst notes", "", notes]
    lines += [
        "",
        "## Reliability warning",
        "",
        "This report is generated by a research software prototype. EBSD vendor conventions, lattice parameters, symmetry settings, parent/child orientation definitions, kinetic parameters, and measured sample-specific data must be validated before publication or industrial decision-making.",
    ]
    return "\n".join(lines)


def build_json_report(model: TwinModel, metrics: dict, gap_report: GapReport | None = None) -> str:
    payload = {
        "generated_utc": datetime.now(timezone.utc).isoformat(),
        "configuration": asdict(model.config),
        "orientation_relationship": {
            "name": model.orientation_relationship.name,
            "parent_phase": model.orientation_relationship.parent_phase,
            "child_phase": model.orientation_relationship.child_phase,
            "matrix_child_to_parent": model.orientation_relationship.matrix_child_to_parent.tolist(),
            "source_note": model.orientation_relationship.source_note,
        },
        "n_variants": len(model.variants),
        "metrics": metrics,
        "gap_report": asdict(gap_report) if gap_report else None,
    }
    return json.dumps(payload, indent=2)
