from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from martwin.core.rotations import misorientation_angle
from .orientation_relationships import OrientationRelationship


@dataclass(frozen=True)
class Variant:
    id: int
    matrix_child_to_parent: np.ndarray
    parent_sym_index: int
    child_sym_index: int = 0


def generate_variants(
    orx: OrientationRelationship,
    parent_sym_ops: list[np.ndarray],
    child_sym_ops: list[np.ndarray] | None = None,
    tol_deg: float = 0.1,
) -> list[Variant]:
    """Generate unique orientation variants from parent symmetry.

    For a fixed parent→child OR, crystallographic variants are generated by the
    lost symmetry operations of the parent phase. Child symmetry is used here only
    to test equivalence between generated orientations. This gives sensible first
    counts for classical fcc→bcc comparisons (e.g. 24-ish KS variants, depending
    on OR convention/refinement) and avoids over-counting P @ R @ C.T combinations.
    """
    unique: list[Variant] = []
    R = orx.matrix_child_to_parent
    for i, P in enumerate(parent_sym_ops):
        M = P @ R
        if not any(misorientation_angle(M, v.matrix_child_to_parent, sym_ops=child_sym_ops) < tol_deg for v in unique):
            unique.append(Variant(id=len(unique) + 1, matrix_child_to_parent=M, parent_sym_index=i, child_sym_index=0))
    return unique


def predict_child_orientations(parent_orientation: np.ndarray, variants: list[Variant]) -> list[np.ndarray]:
    """Predict specimen-frame child orientations from parent orientation.

    If R_cp maps child crystal -> parent crystal, then a possible child orientation
    can be represented as parent_orientation @ R_cp in this internal convention.
    Validate conventions when exchanging with EBSD vendor files or MTEX/orix.
    """
    return [parent_orientation @ v.matrix_child_to_parent for v in variants]


def parent_candidates_from_child(child_orientation: np.ndarray, variants: list[Variant]) -> list[np.ndarray]:
    """Return possible parent orientations from one measured child orientation."""
    return [child_orientation @ v.matrix_child_to_parent.T for v in variants]


def identify_variant_for_known_parent(
    measured_child_orientation: np.ndarray,
    parent_orientation: np.ndarray,
    variants: list[Variant],
    child_sym_ops: list[np.ndarray] | None = None,
) -> dict:
    """Find closest theoretical variant for a known parent orientation."""
    predictions = predict_child_orientations(parent_orientation, variants)
    errors = [misorientation_angle(measured_child_orientation, p, sym_ops=child_sym_ops) for p in predictions]
    idx = int(np.argmin(errors))
    return {
        "variant_id": variants[idx].id,
        "angular_error_deg": float(errors[idx]),
        "parent_sym_index": variants[idx].parent_sym_index,
        "child_sym_index": variants[idx].child_sym_index,
    }
