from __future__ import annotations

from pathlib import Path
from typing import IO

import numpy as np
import pandas as pd

from martwin.core.rotations import bunge_euler_to_matrix, project_to_rotation

REQUIRED_EULER_COLUMNS = ("phi1", "Phi", "phi2")
MATRIX_COLUMNS = tuple(f"r{i}{j}" for i in range(3) for j in range(3))


def dataframe_to_orientation_matrices(df: pd.DataFrame, degrees: bool = True) -> list[np.ndarray]:
    """Extract orientation matrices from an EBSD-like dataframe.

    Supported formats:
    - matrix columns r00..r22 generated by OpenMartensiteTwin;
    - Bunge Euler columns phi1, Phi, phi2.
    """
    if set(MATRIX_COLUMNS).issubset(df.columns):
        mats = []
        for r in df.itertuples(index=False):
            d = r._asdict()
            R = np.array([[d["r00"], d["r01"], d["r02"]], [d["r10"], d["r11"], d["r12"]], [d["r20"], d["r21"], d["r22"]]], dtype=float)
            mats.append(project_to_rotation(R))
        return mats
    if set(REQUIRED_EULER_COLUMNS).issubset(df.columns):
        return [bunge_euler_to_matrix(r.phi1, r.Phi, r.phi2, degrees=degrees) for r in df.itertuples()]
    raise ValueError(
        "CSV requires either matrix columns r00..r22 or Bunge Euler columns phi1, Phi, phi2. "
        f"Columns received: {list(df.columns)}"
    )


def read_ebsd_csv(path_or_buffer: str | Path | IO, degrees: bool = True) -> pd.DataFrame:
    """Read a simple EBSD CSV export.

    Expected columns: x, y plus either r00..r22 or phi1/Phi/phi2. Optional columns:
    phase, grain_id, ci, iq, point_id.
    """
    df = pd.read_csv(path_or_buffer)
    mats = dataframe_to_orientation_matrices(df, degrees=degrees)
    df = df.copy()
    df["orientation_matrix"] = mats
    if "point_id" not in df.columns:
        df["point_id"] = range(len(df))
    if "x" not in df.columns:
        df["x"] = range(len(df))
    if "y" not in df.columns:
        df["y"] = 0
    return df


def write_synthetic_ebsd_csv(path: str | Path, orientations: list[np.ndarray], grid_shape: tuple[int, int] | None = None) -> None:
    """Write synthetic orientations to a CSV with matrix entries, not Euler inversion."""
    n = len(orientations)
    if grid_shape is None:
        grid_shape = (n, 1)
    rows = []
    for idx, R in enumerate(orientations):
        y, x = divmod(idx, grid_shape[1])
        row = {"x": x, "y": y, "phase": "child", "point_id": idx}
        for i in range(3):
            for j in range(3):
                row[f"r{i}{j}"] = float(R[i, j])
        rows.append(row)
    pd.DataFrame(rows).to_csv(path, index=False)


def read_orientation_matrix_csv(path_or_buffer: str | Path | IO) -> list[np.ndarray]:
    df = pd.read_csv(path_or_buffer)
    return dataframe_to_orientation_matrices(df)
